### PR TITLE
contribution faq: "how to fix a failed job"

### PR DESCRIPTION
**Pull request by tknobi**
After fixing markdown linter issues in #19, i thought it's maybe a good idea to tell you how to fix them.
@f-gaul: Would you like to take a look?

### CODE REVIEW

**Comment by tknobi** [comment]
As a proof that failing jobs are normal, here is one :smile: :
https://github.com/bruno-robot/bruno-robot/runs/6644914451?check_suite_focus=true#step:4:118

**Review by f-gaul — APPROVED** [review]
Looks fine. (This linting stuff is also complete new to me)
(You repaired the two errors before I was able to find out how to do it for myself, right? :-) 
For a short while I thought it was a sort of lint-automatic-somewhat-magic ;-) 
I learn something new every time.)

**Comment by f-gaul** [comment]
Ahh.. don't know the difference between 'create a merge commit', 'squash and merge' and 'rebase and merge'.
So, someone with more experience should do this.

**Comment by tknobi** [comment]
> Ahh.. don't know the difference between 'create a merge commit', 'squash and merge' and 'rebase and merge'.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges

>  So, someone with more experience should do this.

i will do it, as a normal merge

**Comment by tknobi** [comment]
>  (You repaired the two errors before I was able to find out how to do it for myself, right? :-)

right :) i requested your review here to inform you about the linter stuff

**Pull request merged**
